config/routes.rb
GeographGenerator::Application.routes.draw do
  match 'console', :to => 'farm#console', :via => :get, :as => :console

  resources :agent_groups, :id => /.+/ do
    member do
      post 'start'
      post 'stop'
      post 'pause'
    end
  end

  resources :dynamic_profiles do
  end

  resources :benchmark_schedules do
    collection do
      post 'set_benchmark'
      put 'play'
      put 'stop'
      delete 'remove_profile'
      put 'sort'
      get 'progress'
      put 'update_iterations'
      put 'update_profile_iterations'
    end
  end

  resources :agents do
    collection do
      get "refresh_time"
    end
  end

  resources :static_profiles do
    member do
      get 'edit_groups'
      put 'update_groups'
      get 'new_group'
      delete 'destroy_group'
    end

    collection do
      post 'create_with_group'
      put 'sort'
    end
  end

  match 'update_profile' => "farm#update_profile"
  match 'delete_profile' => "farm#delete_profile"
  match 'create_benchmark' => "dynamic_profiles#create"
  match 'set_properties' => "farm#choose_process"
  match 'map' => "farm#map"
  devise_for :users, :path_prefix => 'my'
  resources :users

  mount Madmass::Engine => '/madmass', :as => 'madmass_engine'

  root :to => 'farm#console'

  match 'benchmark' => "benchmark_schedules#index"
  

  match 'map_url'=> "settings#map"
  match 'stats_url'=> "settings#stats"

  match 'stats' => "farm#stats"

end

app/controllers/farm_controller.rb
###############################################################################
###############################################################################
#
# This file is part of GeoGraph Agent Farm.
#
# Copyright (c) 2012 Algorithmica Srl
#
# GeoGraph Agent Farm is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GeoGraph Agent Farm is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with GeoGraph Agent Farm.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact us via email at info@algorithmica.it or at
#
# Algorithmica Srl
# Vicolo di Sant'Agata 16
# 00153 Rome, Italy
#
###############################################################################
###############################################################################

class FarmController < ApplicationController
  before_filter :authenticate_agent
  respond_to :js, :html

  around_filter :transact, :only => [:console, :benchmark_tool]

  def index
    @agent = Madmass.current_agent
  end

  def map
    @map_url = "http://madmass-node:8080"
    @map_url = current_user.setting.map_url if current_user.setting
  end

  def stats
    @stats_url = "http://www.algorithmica.it"
    @stats_url = current_user.setting.stats_url if current_user.setting
    Rails.logger.debug("stats url to render is #{@stats_url}")
  end

  def update_profile
    current_user.current_profile = DynamicProfile.find_by_id params[:current_profile_id]
    current_user.save!
    Rails.logger.info("updating profile #{params[:current_profile_id]}")
    render :layout => false
  end

  def delete_profile
    current_user.current_profile.delete if current_user.current_profile
    current_user.current_profile = nil
    current_user.save!
    render :layout => false
  end

  def console
    logger.debug "@@@@@@@@@@@@@@@@@@@@@@@@@@@ 111111111 @@@@@@@@@@@@@@@@@@@@@@@@@@@"
    @agent_groups = CloudTm::AgentGroup.all
    logger.debug "@@@@@@@@@@@@@@@@@@@@@@@@@@@ 222222222 @@@@@@@@@@@@@@@@@@@@@@@@@@@"
    @agent_groups.map(&:getAgents).flatten.each { |el| logger.debug el.inspect }
    @agent_group = CloudTm::AgentGroup.new
    logger.debug "@@@@@@@@@@@@@@@@@@@@@@@@@@@ 333333333 @@@@@@@@@@@@@@@@@@@@@@@@@@@"
    @dynamic_profile = DynamicProfile.new
    logger.debug "@@@@@@@@@@@@@@@@@@@@@@@@@@@ 444444444 @@@@@@@@@@@@@@@@@@@@@@@@@@@"

    @user = current_user
    @profiles = []
    if current_user.current_profile
      @profiles << [current_user.current_profile.name, current_user.current_profile.id]
    end
    current_user.dynamic_profiles.each do |p|
      @profiles << [p.name, p.id] unless (p == current_user.current_profile)
    end

  end

  def choose_process
    options = {}
    options[:name] = params[:id] if params[:id]
    options[:distance] = params[:distance] if params[:distance]
    Job.new.set(options)
  end

  private


  def transact
    CloudTm::FenixFramework.getTransactionManager.withTransaction do
      yield
    end
  end


end

app/helpers/farm_helper.rb
###############################################################################
###############################################################################
#
# This file is part of GeoGraph Agent Farm.
#
# Copyright (c) 2012 Algorithmica Srl
#
# GeoGraph Agent Farm is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GeoGraph Agent Farm is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with GeoGraph Agent Farm.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact us via email at info@algorithmica.it or at
#
# Algorithmica Srl
# Vicolo di Sant'Agata 16
# 00153 Rome, Italy
#
###############################################################################
###############################################################################

module FarmHelper
end

app/views/farm/add_static_profile.html.erb
<%= render 'shared/profile_details' %>

app/views/farm/console.html.erb
<div class=" row-fluid">

  <div class='span5 sandbox'>

    <div class="row-fluid">
      <div class="span12">
        <h3>WORKLOAD SANDBOX</h3>
      </div>
    </div>

    <div class="row-fluid">
      <div class="span2 btn-group">
        <%= button_tag "new group", :class => 'btn btn-primary', :id => 'new-agent-group-button' %>
      </div>

      <div class="input-prepend offset1 span9">
        <%= button_tag "to benchmark", :class => 'btn', :type => "button", :id => 'create-static-profile-with-group' %>
        <input id="appendedInputButton" class="span6" type="text" placeholder="with duration (in minutes)">
      </div>
    </div>

    <br/>

    <div class="row-fluid">
      <div id='agent-groups' class="span12">
        <%= render 'agent_groups/index' %>
      </div>
    </div>

  </div>

  <div class='span7 sandbox'>
    <div class="row-fluid">
      <div class="span12">
        <h3>CURRENT BENCHMARK</h3>
      </div>
    </div>

    <div class="row-fluid">
      <div class="input-prepend span4 btn-low">
        <%= button_tag "create", :class => 'btn', :type => "button", :id => 'create-benchmark' %>
        <input id="benchmark_name" class="span9" type="text" placeholder="benchmark name">
      </div>


      <div class="span2">
        <h4>or select an</h4>
      </div>
      <div class="span4 btn-low">
        <%= select_tag "current_benchmark_id", options_for_select(@profiles), :prompt => "existing benchmark" %>
      </div>
    </div>

    <div id="current_profile_details" class="row-fluid">
      <%= render 'shared/profile_details' %>
    </div>
    <%= render 'shared/new_static_profile' %>
    <%= render 'shared/edit_static_profile' %>
  </div>


</div>

<!-- Modal -->
<div id="new-group-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="addAgentGroup" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="addAgentGroup">New Agent Group</h3>
  </div>

  <%= form_for :agent_group, :url => agent_groups_path(@agent_group), :remote => true, :html => {:id => :new_agent_group} do |f| %>
    <fieldset>
      <div class="modal-body row">  
          <label for="agents" class="span2">Agents Type</label>
          <%= f.select :agents_type, AGENT_TYPES.map { |at| [at.sub(/Agent$/, '').downcase, at] }, {}, :class => "" %>

          <label for="agents" class="span2">Agents</label>
          <%= number_field_tag 'agent_group[agents]', 0, :in => 0...100000 %>

          <label for="delay" class="span2">Delay</label>
          <%= number_field_tag 'agent_group[delay]', 0, :in => 0...100000 %>
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <%= submit_tag 'Add', :class => 'btn btn-primary' %>
      </div>
    </fieldset>
  <% end %> 
</div>


<script>
  $(document).ready(function() {
      $('#new-agent-group-button').on('click', function() {
        newGroup();
      });

      $('#new_agent_group').on('submit', function() {
        $('#new-group-modal').modal('hide');
      });

    $('#create-static-profile-with-group').on('click', function() {
      $.ajax({
        url: 'static_profiles/create_with_group', 
        type: 'POST',
        data: {'duration': $('#appendedInputButton').val()}
      }).done(function(details) {
        $('#current_profile_details').html(details);
      });
    });

    $('#create-benchmark').on('click', function() {
      $.ajax({
        url: 'create_benchmark', 
        type: 'PUT',
        data: {'name': $('#benchmark_name').val()}
      }).done(function(details) {
        $('#current_profile_details').html(details);
      });              
    });

    $('#current_benchmark_id').on('change', function() {
      $.ajax({
        url: 'update_profile',
        type: 'PUT',
        data: {'current_profile_id': $(this).val()}
      }).done(function(details) {
        $('#current_profile_details').html(details);
      });
    });

  });
</script>

app/views/farm/create_profile.html.erb
<%= render 'shared/profile_details' %>

app/views/farm/delete_profile.html.erb
<%= render 'shared/profile_details' %>

app/views/farm/index.html.erb
<!-- registering with socky message server on the public channel move -->
<%#= register_socky(:channels => ['move']) %>

<!-- a simple heading title -->
<h1>Geograph Generator remote move test</h1>
agent status: <%= @agent.status %>

<!-- an edit box using the rails `text_field_tag` helper -->
<%= text_field_tag 'latitude', nil %>
<%= text_field_tag 'longitude', nil %>
<%= button_tag 'start', :onclick => "sendStart(event);" %>
<%= button_tag 'stop', :onclick => "sendStop(event);" %>

<script type="text/javascript">

  // the javascript function registered to _onkeyup_ of the edit box.
  function sendStart(event){

    //var lat = $('#latitude').val();
    //var lon = $('#longitude').val();
    // send message
    
    //ask an agent, through the commands agent controller
    //to perform Actions::ProxyMoveAction with parameters latitude and longitude
    $askAgent({ agent: 'geoggen/commands', cmd: 'start' });

    //and clear the input box
    //$('#new-message').val('');
    
  }

  function sendStop(event){
    $askAgent({ agent: 'geoggen/commands', cmd: 'stop' });
  }
</script>

<!-- creating a simple messages box with a div and some basic inline style -->
<div class="messages" style="background-color: #FCEED8; border: 1px solid #A9A9A9">
  Move messages:
</div>

app/views/farm/map.html.erb
<div class="row-fluid">
  <iframe class="map span12" src="<%= @map_url%>">></iframe>
</div>

app/views/farm/stats.html.erb
<div class="row-fluid">
  <iframe class="map span12" src="<%= @stats_url%>">></iframe>
</div>

app/views/farm/update_profile.html.erb
<%= render 'shared/profile_details' %>