config/routes.rb
GeographGenerator::Application.routes.draw do
  match 'console', :to => 'farm#console', :via => :get, :as => :console

  resources :agent_groups, :id => /.+/ do
    member do
      post 'start'
      post 'stop'
      post 'pause'
    end
  end

  resources :dynamic_profiles do
  end

  resources :benchmark_schedules do
    collection do
      post 'set_benchmark'
      put 'play'
      put 'stop'
      delete 'remove_profile'
      put 'sort'
      get 'progress'
      put 'update_iterations'
      put 'update_profile_iterations'
    end
  end

  resources :agents do
    collection do
      get "refresh_time"
    end
  end

  resources :static_profiles do
    member do
      get 'edit_groups'
      put 'update_groups'
      get 'new_group'
      delete 'destroy_group'
    end

    collection do
      post 'create_with_group'
      put 'sort'
    end
  end

  match 'update_profile' => "farm#update_profile"
  match 'delete_profile' => "farm#delete_profile"
  match 'create_benchmark' => "dynamic_profiles#create"
  match 'set_properties' => "farm#choose_process"
  match 'map' => "farm#map"
  devise_for :users, :path_prefix => 'my'
  resources :users

  mount Madmass::Engine => '/madmass', :as => 'madmass_engine'

  root :to => 'farm#console'

  match 'benchmark' => "benchmark_schedules#index"
  

  match 'map_url'=> "settings#map"
  match 'stats_url'=> "settings#stats"

  match 'stats' => "farm#stats"

end

app/views/shared/_benchmark_profile_list.html.erb
<% if static_profiles %>
  <% static_profiles.each_with_index do |profile, index| %>
    <div class="accordion-group" data-profile="<%= profile.id %>">
      
      <div class="accordion-heading">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#<%= accordion_id %>" href="#collapse<%= profile.id %>">
          <%= "profile #{profile.id} (#{profile.duration} min)".html_safe %>
          <div class="progress progress-info progress-striped" style="width: 150px; display: inline-block; margin: 0 0 0 20px; float: right;">
            <% progress = @progress_data[:static_profiles][profile.id][:progress] %>
            <div id="static-profile-progress-<%= profile.id %>" class="bar" style="width: <%= progress %>%"><%= progress %>%</div>
          </div>
        </a>

      </div>
      
      <div id="collapse<%= profile.id %>" class="accordion-body collapse">
        <div class="accordion-inner">
          
          <table class="table table-striped">
            <thead>
              <tr>
                <th>simulator</th>
                <th># threads</th>
                <th>sleep (msec)</th>
                <!-- <th>% progress</th> -->
              </tr>
            </thead>
            <tbody>
              <% profile.agent_groups.each do |agent_group| %>
                <tr>
                  <td><%= agent_group.simulator %></td>
                  <td><%= agent_group.threads %></td>
                  <td><%= agent_group.sleep %></td>
              <% end %>
            </tbody>
          </table>

        </div>
      </div>

    </div>
  <% end %>
<% end %>

app/views/shared/_edit_static_profile.html.erb
<!-- Modal -->
<div id="update-static-profile-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="updateStaticProfile" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="updateStaticProfile">Modify Static Profile</h3>
  </div>

  <%= form_tag 'static_profiles/1', :id => 'update-static-profile-form', :method => 'put', :remote => true do %>
    <fieldset>
      <div class="modal-body">  
          <%= label_tag(:duration, 'Duration') %>
          <%= text_field_tag "static_profile[duration]", '', :placeholder => 'in minutes' %>
          <%= hidden_field_tag "id", '' %>
      </div>

      <div id="static-profile-groups" class="modal-body">
      </div>

      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <%= submit_tag 'Save', :class => 'btn btn-primary' %>
      </div>
    </fieldset>
  <% end %> 
</div>

<script>
  $(document).ready(function() {
    $('#update-static-profile-modal').on('click', '#add-group-button', function() {
      $.ajax({
        url: 'static_profiles/' + $(this).data('profile') + '/new_group'
      }).done(function(data) {
        $('.group-container').append(data);
      });
    });

    $('#update-static-profile-modal').on('click', '.delete-agent-group-button', function() {
      var groupId = $(this).data('group');
      $.ajax({
        url: 'static_profiles/' + groupId + '/destroy_group',
        type: 'delete'
      }).done(function(data) {
        $('#current_profile_details').html(data);
        $('#group-for-' + groupId).remove();
      });
    });

    $('#update-static-profile-modal').on('click', '.save-agent-group-simulator', function() {
      var groupId = $(this).data('group');
      var simulator = $(this).parent().find('#agent_group_simulator').val();
      $.ajax({
        url: 'static_profiles/' +  groupId + '/update_groups',
        data: {attribute: 'simulator', value: simulator},
        type: 'put'
      }).done(function(data) {
        $('#current_profile_details').html(data);
        addAlertSuccess(groupId);
      });
    });

    $('#update-static-profile-modal').on('click', '.save-agent-group-threads', function() {
      var groupId = $(this).data('group');
      var threads = $(this).parent().find('#agent_group_threads').val();
      $.ajax({
        url: 'static_profiles/' +  groupId + '/update_groups',
        data: {attribute: 'threads', value: threads},
        type: 'put'
      }).done(function(data) {
        $('#current_profile_details').html(data);
        addAlertSuccess(groupId);
      });
    });

    $('#update-static-profile-modal').on('click', '.save-agent-group-sleep', function() {
      var groupId = $(this).data('group');
      var sleep = $(this).parent().find('#agent_group_sleep').val();
      $.ajax({
        url: 'static_profiles/' +  groupId + '/update_groups',
        data: {attribute: 'sleep', value: sleep},
        type: 'put'
      }).done(function(data) {
        $('#current_profile_details').html(data);
        addAlertSuccess(groupId);
      });
    });

  });

  function addAlertSuccess(groupId) {
    var alertDom = $('#form-success').clone();
    var container = $('#group-for-' + groupId);
    container.find('.static-profile-form-success').remove();
    container.prepend(alertDom);
    var formAlert = container.find('.static-profile-form-success');
    formAlert.removeClass('hidden');
    formAlert.show();
  }
  
</script>

app/views/shared/_header.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <div class="row-fluid">
        <a class="brand" href="#">Geograph Farm</a>

        <div class="nav-collapse collapse navbar-responsive-collapse">
          <ul class="nav span7">
            <li><%= link_to "editor", console_path %></li>
            <li><%= link_to "benchmark", benchmark_path %></li>
            <li><%= link_to "stats", stats_path %></li>
            <li><%= link_to "inspect", agents_path %></li>
            <li><%= link_to "map", map_path %></li>
            <li class="dropdown closed bigmenu">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">settings <b class="caret"></b></a>

              <ul class="dropdown-menu row-fluid">

                <li class="divider"></li>
                <li class="nav-header">EDGE PROCESSOR</li>
                <%= select_tag "current_profile_id", options_for_select(['none', 'job', 'action']), :prompt => "processor type", :class => 'span10 edge_processor_type'
                %>

                <li>
                  <label class="edge_processor_type" for="name">
                    distance <span id="distance-selected-new"><%= 0 %></span> (mt)
                  </label>
                </li>
                <%= hidden_field_tag "process[distance]" %>

                <li>
                  <div class="distance-slider slider edge_processor_type" rel="new"></div>
                </li>

                <li class="span12">
                  <%= button_tag "save", :class => 'btn btn-primary btn-mini dropdown-save', :onclick => "$.ajax({
                                                                                         url: '#{set_properties_path}',
                                                                                         type: 'PUT',
                                                                                         data: {'distance': $('#process_distance').val(), 'id': $('#current_profile_id').val() },
                                                                                         success: function(details){
                                                                                         }
                                                                                       });" %>
                </li>

                <li class="divider divider-hack"></li>
                <li class="nav-header">MAP URL</li>
                <li>
                  <form class="navbar-form pull-left url-box">
                    <input id="map-url" type="text" placeholder="http://example.com:8080" value="<%= current_user ? current_user.setting.map_url : nil %>"/>
                  </form>
                </li>

                <li class="span12">
                  <%= button_tag "save", :class => 'btn btn-primary btn-mini dropdown-save',
                                 :onclick => "$.ajax({
                                                url: '#{map_url_path}',
                                                type: 'PUT',
                                                data: {'map_url': $('#map-url').val()}});" %>
                </li>
                <li class="divider divider-hack"></li>
                <li class="nav-header">STATS URL</li>
                <li>
                  <form class="navbar-form pull-left url-box">
                    <input id="stats-url" type="text" placeholder="http://example.com:8080" value="<%= current_user ? current_user.setting.stats_url : nil %>">
                  </form>
                </li>
                <li class="span12">
                  <%= button_tag "save", :class => 'btn btn-primary btn-mini dropdown-save', :onclick => "$.ajax({
                                                                  url: '#{stats_url_path}',
                                                                  type: 'PUT',
                                                                  data: {'stats_url': $('#stats-url').val()}});" %>
                </li>

              </ul>
            </li>
          </ul>
          </li>
          </ul>
          <ul class="nav span3">
            <% if user_signed_in? %>
              <li class="sign-out"><%= link_to "Sign out #{current_user.email}", destroy_user_session_path, :method => :delete %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_new_static_profile.html.erb
<!-- Modal -->
<div id="static-profile-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="addStaticProfile" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="addStaticProfile">Add Static Profile</h3>
  </div>

  <%= form_tag 'static_profiles', :id => 'static-profile-form', :method => 'post', :remote => true do %>
    <fieldset>
      <div class="modal-body">  
          <%= label_tag(:duration, 'Duration') %>
          <%= text_field_tag :duration, '', :placeholder => 'in minutes' %>
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <%= submit_tag 'Add', :class => 'btn btn-primary' %>
      </div>
    </fieldset>
  <% end %> 
</div>


<div id="form-alert" class="alert alert-error hidden static-profile-form-alert">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <h4>Warning!</h4>
  Use numeric value for duration!
</div>


<div id="form-success" class="alert alert-success hidden static-profile-form-success">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <h4>Success</h4>
  Saved!
</div>

app/views/shared/_profile_details.html.erb
<% if (current_user.current_profile) %>
  <h4> NAME: <%= current_user.current_profile.name.upcase %>
     <%= link_to "add", '#static-profile-modal', 
                :class => 'add-static-profile-button btn btn-mini btn-success', 
                :type => "button", 
                :data => {:toggle => 'modal'} -%>
     <%= button_tag "delete", :class => 'btn btn-mini btn-danger', :type => "button", :id => 'delete-benchmark' %>
   </h4>

  <%= render :partial => 'shared/profile_list', 
             :locals => { :static_profiles => current_user.current_profile.static_profiles, :accordion_id => 'console-accordion' } %>
<% end %>

<script>
  $(document).ready(function() {
    $('#console-accordion').sortable({
      stop: function() {
        var sortedProfiles = [];
        $('#console-accordion').find('.accordion-group').each(function(index, elem) {
          sortedProfiles.push($(elem).data('profile'));
        });

        $.ajax({
          url: 'static_profiles/sort',
          type: 'put',
          data: {ids: sortedProfiles}
        })
      }
    });

    $('#delete-benchmark').on('click', function() {
      if(confirm("Are you sure you want delete benchmarck")) {
        $.ajax({
          url: 'delete_profile',
          type: 'PUT'
        }).done(function(details) {
           $('#current_profile_details').html(details);
        });
      }
    });

    $('.icon-trash').on('click', function(event) {
      event.stopPropagation();
      var icon = $(this);
      if(confirm("Are you sure you want delete profile " + icon.data('profile') +' ?')) {
        $.ajax({
          url: 'static_profiles/' + icon.data('profile'),
          type: 'delete'
        }).done(function(details) {
          $('#current_profile_details').html(details);
        });
      } 
    });

    $('.icon-edit').on('click', function(event) {
      event.stopPropagation();
      var icon = $(this);
      var profileId = icon.data('profile');
      var duration = icon.data('duration');

      $.ajax({
        url: 'static_profiles/' + profileId + '/edit_groups',
        async: false
      }).done(function(groups) {
        $('#static-profile-groups').html(groups);
      });

      $('#static_profile_duration').val(duration);
      $('#id').val(profileId);
      var action = $('#update-static-profile-form').attr('action');
      $('#update-static-profile-form').attr('action', action.replace(/\/\d+/, '/' + profileId));
      $('#update-static-profile-modal').modal('show');
    });

    $('#static-profile-form').on('ajax:complete', function(event, data) {
      $('#static-profile-modal').modal('hide');
      $('#current_profile_details').html(data.responseText);
    }).on('submit', function() {
      if(parseInt($(this).find('#duration').val())) {
        return true;
      } else {
        var alertDom = $('#form-alert').clone();
        $('#static-profile-form').parent().find('.static-profile-form-alert').remove();
        $('#static-profile-form').prepend(alertDom);
        var formAlert = $('#static-profile-form').parent().find('.static-profile-form-alert');
        formAlert.removeClass('hidden');
        formAlert.show();
        return false;
      }
    });

    $('#update-static-profile-form').on('ajax:complete', function(event, data) {
      $('#update-static-profile-modal').modal('hide');
      $('#current_profile_details').html(data.responseText);
    }).on('submit', function() {
      if(parseInt($(this).find('#static_profile_duration').val())) {
        return true;
      } else {
        var alertDom = $('#form-alert').clone();
        $('#update-static-profile-form').parent().find('.static-profile-form-alert').remove();
        $('#update-profile-form').prepend(alertDom);
        var formAlert = $('#static-profile-form').parent().find('.static-profile-form-alert');
        formAlert.removeClass('hidden');
        formAlert.show();
        return false;
      }
      
    });
  });
</script>

app/views/shared/_profile_list.html.erb
<div class="span10  accordion" id="<%= accordion_id %>">
<% if static_profiles %>
  <% static_profiles.each do |profile| %>
    <div class="accordion-group" data-profile="<%= profile.id %>">
      <div class="accordion-heading">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#<%= accordion_id %>" href="#collapse<%= profile.position %>">
          <%= "profile #{profile.id} (#{profile.duration} min)".html_safe %>
          <i class="static-profile-action icon-trash" data-profile="<%= profile.id %>"></i>
          <i class="static-profile-action icon-edit" data-profile="<%= profile.id %>" data-duration="<%= profile.duration %>"></i>              
        </a>
      </div>
      <div id="collapse<%= profile.position %>" class="accordion-body collapse">
        <div class="accordion-inner">
          <table class="table table-striped">
            <thead>
            <tr>
              <th>simulator</th>
              <th># threads</th>
              <th>sleep (msec)</th>
            </tr>
            </thead>
            <tbody>
            <!-- FIXME -->
            <% profile.agent_groups.each do |agent_group| %>
              <tr>
                <td><%= agent_group.simulator %></td>
                <td><%= agent_group.threads %></td>
                <td><%= agent_group.sleep %></td>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  <% end %>
<% end %>
</div>