config/routes.rb
GeographGenerator::Application.routes.draw do
  match 'console', :to => 'farm#console', :via => :get, :as => :console

  resources :agent_groups, :id => /.+/ do
    member do
      post 'start'
      post 'stop'
      post 'pause'
    end
  end

  resources :dynamic_profiles do
  end

  resources :benchmark_schedules do
    collection do
      post 'set_benchmark'
      put 'play'
      put 'stop'
      delete 'remove_profile'
      put 'sort'
      get 'progress'
      put 'update_iterations'
      put 'update_profile_iterations'
    end
  end

  resources :agents do
    collection do
      get "refresh_time"
    end
  end

  resources :static_profiles do
    member do
      get 'edit_groups'
      put 'update_groups'
      get 'new_group'
      delete 'destroy_group'
    end

    collection do
      post 'create_with_group'
      put 'sort'
    end
  end

  match 'update_profile' => "farm#update_profile"
  match 'delete_profile' => "farm#delete_profile"
  match 'create_benchmark' => "dynamic_profiles#create"
  match 'set_properties' => "farm#choose_process"
  match 'map' => "farm#map"
  devise_for :users, :path_prefix => 'my'
  resources :users

  mount Madmass::Engine => '/madmass', :as => 'madmass_engine'

  root :to => 'farm#console'

  match 'benchmark' => "benchmark_schedules#index"
  

  match 'map_url'=> "settings#map"
  match 'stats_url'=> "settings#stats"

  match 'stats' => "farm#stats"

end

app/models/agent_group.rb
class AgentGroup < ActiveRecord::Base
  attr_accessible :simulator, :sleep, :static_profile_id, :threads, :cache_id
  belongs_to :static_profile
  include Madmass::Transaction::TxMonitor


  def deploy
    group_options ={"agents_type" => simulator, "delay" => sleep, "status" => "idle"}
    Madmass.logger.debug "DEPLOY: About to create group -- #{threads} agents #{group_options.inspect}--"

    tx_monitor do
      @agent_group = CloudTm::AgentGroup.create_group(threads, group_options)
      Madmass.logger.info "DEPLOY: Created agent group with id #{@agent_group.id} -- #{@agent_group.inspect}"
      self.cache_id = @agent_group.id
      save!
      Madmass.logger.debug "DEPLOY: Agentgroup Cache id saved"
    end

    tx_monitor do
      Madmass.logger.debug "DEPLOY: Retrieving agent group with cache id #{self.cache_id}"
      CloudTm::AgentGroup.boot(:agent_group_id => self.cache_id)
    end
  end

  def start
    tx_monitor do
      agent_group = CloudTm::AgentGroup.find_by_id self.cache_id
      # agent_group.update_attribute(:status, 'started')
      Madmass.logger.debug "STARTING AGENT GROUP #{agent_group.inspect}"
      if agent_group
        agent_group.start
      else
        Madmass.logger.error "DEPLOY: Could not find agent group #{self.cache_id}"
      end

    end
  end

  def shutdown
    tx_monitor do
      Madmass.logger.debug "SHUTTING DOWN AGENT GROUP #{self.cache_id}"
      agent_group = CloudTm::AgentGroup.find_by_id self.cache_id
      ##terminates all the background tasks, one per each agent of the group
      if agent_group
        agent_group.shutdown
      else
        Madmass.logger.error "DEPLOY: Could not find agent group #{self.cache_id}"
      end

    end
  end


end

app/controllers/agent_groups_controller.rb
###############################################################################
###############################################################################
#
# This file is part of GeoGraph Agent Farm.
#
# Copyright (c) 2012 Algorithmica Srl
#
# GeoGraph Agent Farm is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GeoGraph Agent Farm is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with GeoGraph Agent Farm.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact us via email at info@algorithmica.it or at
#
# Algorithmica Srl
# Vicolo di Sant'Agata 16
# 00153 Rome, Italy
#
###############################################################################
###############################################################################

class AgentGroupsController < ApplicationController
  include Madmass::Transaction::TxMonitor


  before_filter :authenticate_agent
  #around_filter :tx_monitor, :except => :boot
  #append_after_filter :boot, :only => [:create]

  around_filter :controller_monitor, :except => :create

  respond_to :html, :js

  def index
    respond_with(@agent_groups = CloudTm::AgentGroup.all)
  end


  # It creates a group of idle agents.
  def create

    group_id = nil

    tx_monitor do
      CloudTm::Route.load_routes #FIXME: Move at benchmark service boot

      #process params
      group_options = params[:agent_group].clone
      group_options[:delay] = group_options[:delay].to_i
      group_options[:status] = 'idle'
      agents = group_options.delete(:agents)

      #Create Group
      Madmass.logger.debug "CREATE: About to create group -- #{agents.inspect} / #{group_options.inspect}--"
      @agent_group = CloudTm::AgentGroup.create_group(agents, group_options)
      Madmass.logger.info "CREATE: Created agent group with id #{@agent_group.id} -- #{@agent_group.inspect}"
      Madmass.logger.debug "CREATE: Retrieving all groups"

      group_id = @agent_group.id
      @agent_groups = CloudTm::AgentGroup.all
    end

    CloudTm::AgentGroup.boot(:agent_group_id => group_id)
  end


#def update
#  group_options = params[:agent_group].clone
#  group_options[:delay] = group_options[:delay].to_i
#  group_options[:agents_type] = "#{group_options[:agents_type].classify}Agent"
#  agents = group_options.delete(:agents)
#  @agent_group = CloudTm::AgentGroup.where(:id => params[:id].to_i).first
#  @agent_group.modify(agents.to_i, group_options)
#  @agent_groups = CloudTm::AgentGroup.all
#  respond_with(@agent_group)
#end

  def destroy
    agent_group = CloudTm::AgentGroup.where(:id => params[:id]).first
    ##terminates all the background tasks, one per each agent of the group
    agent_group.shutdown

    @agent_groups = CloudTm::AgentGroup.all
  end

  def start
    agent_group = CloudTm::AgentGroup.where(:id => params[:id]).first
    # agent_group.update_attribute(:status, 'started')
    Madmass.logger.debug "STARTING AGENT GROUP #{agent_group.inspect}"
    agent_group.start if agent_group
    @agent_groups = CloudTm::AgentGroup.all
  end

  def stop
    agent_group = CloudTm::AgentGroup.where(:id => params[:id]).first
    #agent_group.update_attributes(:status => 'stopped', :last_execution => nil) if agent_group
    agent_group.stop if agent_group
    @agent_groups = CloudTm::AgentGroup.all
  end

  def pause
    agent_group = CloudTm::AgentGroup.where(:id => params[:id]).first
    agent_group.update_attribute(:status, 'paused') if agent_group
    agent_group.pause if agent_group
    @agent_groups = CloudTm::AgentGroup.all
  end

  private
  def controller_monitor
    tx_monitor do
      yield
    end
    #boot if self.action_name == 'create'
    return
  end

  #def boot()
  #  Madmass.logger.debug "############################# BOOT START #############################"
  #
  #  retries = 0
  #
  #  begin
  #    agents_ids = []
  #    delay = 5
  #    type = nil
  #    tx_monitor do
  #      agent_group = CloudTm::AgentGroup.find_by_id(@agent_group_id)
  #      unless agent_group
  #        message = "Did not find agent group with id (#{@agent_group_id})"
  #        Madmass.logger.error message
  #        raise Madmass::Errors::WrongInputError.new message
  #      end
  #
  #      delay = agent_group.delay
  #      type = agent_group.agents_type
  #      agent_group.getAgents.each do |agent|
  #        Madmass.logger.debug "Found agent in group: #{agent.inspect}"
  #        agents_ids << agent.getExternalId
  #      end
  #      Madmass.logger.info "Agent group and agents found"
  #      #agent_group.boot #Starts a background tasks for each agent
  #    end
  #  rescue Madmass::Errors::WrongInputError => ex
  #    raise Madmass::Errors::CatastrophicError.new "Did not find agent group #{@agent_group_id}, retries limit reached" if retries > 10
  #    Madmass.logger.error "retrying #{retries}-th time..."
  #    retries +=1
  #    java.lang.sleep((10*retries)**2)
  #    retry
  #  end
  #
  #
  #  Madmass.logger.info "Starting #{agents_ids.size} simulations"
  #
  #  simulator_opts ={
  #    :tx => false,
  #    :persistent => false,
  #    #:priority => :critical
  #  }
  #
  #  scatter_time = 15 #ms
  #  Madmass.logger.debug("Type: #{type}")
  #
  #  klass_name = "CloudTm::#{type}"
  #
  #  klass = klass_name.constantize
  #  raise Madmass::Errors::CatastrophicError, "#{klass_name} does not include Madmass::AgentFarm::Agent::AutonomousAgent" unless klass.included_modules.include?(Madmass::AgentFarm::Agent::AutonomousAgent)
  #
  #  agents_ids.each do |agent_id|
  #
  #    klass.background(simulator_opts).simulate(
  #      {:agent_id => agent_id,
  #       :step => delay,
  #       :agent_group_id => @agent_group_id}
  #    )
  #    Madmass.logger.debug("******* Agent(group:#{@agent_group_id} -- id:#{agent_id}) launched *******")
  #    java.lang.Thread.sleep(rand*scatter_time);
  #  end
  #  Madmass.logger.debug "############################# BOOT END #############################"
  #end


end

app/helpers/agent_groups_helper.rb
###############################################################################
###############################################################################
#
# This file is part of GeoGraph Agent Farm.
#
# Copyright (c) 2012 Algorithmica Srl
#
# GeoGraph Agent Farm is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GeoGraph Agent Farm is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with GeoGraph Agent Farm.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact us via email at info@algorithmica.it or at
#
# Algorithmica Srl
# Vicolo di Sant'Agata 16
# 00153 Rome, Italy
#
###############################################################################
###############################################################################

module AgentGroupsHelper
end

app/views/agent_groups/_choose.html.erb
<% agent_group.possible_actions.each do |action| %>
  <%= button_tag action, :class => "button-action", :onclick => "#{action}Group(#{agent_group.to_json});" do %>
    <%#= image_tag "#{action}.jpg", :border => 0, :title => action %>
    <% case action %>
    <% when 'start' %>
      <i class="icon-play"></i>
    <% when 'stop' %>
      <i class="icon-stop"></i>
    <% when 'destroy' %>
      <i class="icon-eject"></i>
    <% when 'pause' %>
      <i class="icon-pause"></i>
    <% else %>
      <i class=" icon-warning-sign"></i> Error!
    <% end %>
  <% end %>
<% end %>

app/views/agent_groups/_index.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th>simulator</th>
    <th>threads</th>
    <th>sleep (msec)</th>
    <th>status</th>
    <th>actions</th>

  </tr>
  </thead>
  <tbody>
  <% (@agent_groups || []).each do |agent_group| %>
    <tr>
      <td>
        <% unless agent_group.started? %>
          <%= link_to agent_group.agents_type, 'javascript:void(0);', :onclick => "editGroup(#{agent_group.to_json});" %>
        <% else %>
          <%= agent_group.agents_type %>
        <% end %>
      </td>
      <td><%= agent_group.agents.size %></td>
      <td><%= agent_group.delay %></td>
      <td class="status-<%= agent_group.status %>"><%= agent_group.status %></td>
      <td>
        <%= render 'agent_groups/choose', :agent_group => agent_group %>
      </td>
      <!--
      <td>
        <%#= agent_group.agents.select { |agent| agent.status == "running" }.size %>
      </td>
      <td>
        <%#= agent_group.agents.select { |agent| agent.status == "stopped" }.size %>
      </td>
      <td>
        <%#= agent_group.agents.select { |agent| agent.status == "paused" }.size %>
      </td>
      <td>
        <%#= agent_group.agents.select { |agent| agent.status == "zombie" }.size %>
      </td>
      <td>
        <%#= agent_group.agents.select { |agent| agent.status == "dead" }.size %>
      </td>
    </tr>
-->
    <div id="edit-group-<%= agent_group.id %>" style="display: none;">
      <%= form_for(:agent_group, :url => agent_group_path(agent_group.id), :remote => true, :method => :put, :html => {:id => "edit-agent-group-#{agent_group.id}"}) do |f| %>
        <label for="name">name</label>
        <%= text_field_tag "agent_group[name]", agent_group.name, :class => "text ui-widget-content ui-corner-all" %>
        <br/>
        
        <label for="type">agents type</label>
        <% agent_type = agent_group.agents_type.blank? ? AGENT_TYPES.first.sub(/Agent$/, '').downcase : agent_group.agents_type.sub(/Agent$/, '').downcase %>
        <% logger.debug "@@@@@@@@@@@@@@@@@@@@@@@@@@@ 555555555555 @@@@@@@@@@@@@@@@@@@@@@@@@@@" %>
        <% logger.debug "@@@@@@@@@@@@@@@@@@@@@@@@@@@ #{agent_type} @@@@@@@@@@@@@@@@@@@@@@@@@@@" %>
        <%= text_field_tag "agent_group[agents_type]", agent_type, :readonly => true, :class => "ui-text-readonly" %>
        <br/>

        <label for="name">agents <span id="agents-selected-<%= agent_group.id %>"><%= agent_group.agents_count %></span></label>
        <%= hidden_field_tag "agent_group[agents]", agent_group.agents_count %>
        <div class="agents-slider slider" rel="<%= agent_group.id %>"></div>
        <br/>

        <label for="name">delay <span id="delay-selected-<%= agent_group.id %>"><%= agent_group.delay %></span>
          (ms)</label>
        <%= hidden_field_tag "agent_group[delay]", agent_group.delay %>
        <div class="delay-slider slider" rel="<%= agent_group.id %>"></div>
      <% end %>
    </div>

  <% end %>
  </tbody>
</table>

app/views/agent_groups/create.js.erb
$('#agent-groups').html('<%= escape_javascript(render :partial => 'index') %>');
//JTable.Setup();
loadSliders();

app/views/agent_groups/destroy.js.erb
$('#agent-groups').html('<%= escape_javascript(render :partial => 'index') %>');
//JTable.Setup();
loadSliders();

app/views/agent_groups/pause.js.erb
$('#agent-groups').html('<%= escape_javascript(render :partial => 'index') %>');
//JTable.Setup();
loadSliders();

app/views/agent_groups/start.js.erb
$('#agent-groups').html('<%= escape_javascript(render :partial => 'index') %>');
//JTable.Setup();
loadSliders();

app/views/agent_groups/stop.js.erb
$('#agent-groups').html('<%= escape_javascript(render :partial => 'index') %>');
//JTable.Setup();
loadSliders();

app/views/agent_groups/update.js.erb
$('#agent-groups').html('<%= escape_javascript(render :partial => 'index') %>');
//JTable.Setup();
loadSliders();